import type {
  NativeHarnessCapability,
  NativeHarnessCapabilityState,
  NativeHarnessDescriptor,
} from "@/shared/crafting";

function capabilityMap(
  declared: readonly NativeHarnessCapability[],
  unsupported: readonly NativeHarnessCapability[] = [],
  integrated: readonly NativeHarnessCapability[] = [],
): Record<string, NativeHarnessCapabilityState> {
  const result: Record<string, NativeHarnessCapabilityState> = {};
  for (const capability of declared) result[capability] = "implementation missing";
  for (const capability of unsupported) result[capability] = "native unsupported";
  // Only provider-native product-path evidence may move a capability out of
  // the conservative default above. Fixture/unit evidence alone is excluded.
  for (const capability of integrated) result[capability] = "supported+integrated";
  return result;
}

const COMMON_STRUCTURED_CAPABILITIES = [
  "discovery",
  "auth",
  "profile",
  "start",
  "resume",
  "multi_turn",
  "streaming",
  "events",
  "tool_execution",
  "file_access",
  "shell_execution",
  "permission",
  "skills",
  "interrupt",
  "cleanup",
  "diagnostics",
] as const satisfies readonly NativeHarnessCapability[];

export const CODEX_NATIVE_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:codex",
  harnessKind: "codex",
  label: "Codex Native Harness",
  vendor: "openai",
  official: true,
  transport: "codex-app-server-json-rpc",
  machineFacingBoundary: "codex app-server --stdio",
  capabilities: capabilityMap(
    [...COMMON_STRUCTURED_CAPABILITIES, "mcp", "subagents", "context", "compaction"],
    [],
    [
      "discovery",
      "auth",
      "start",
      "resume",
      "multi_turn",
      "streaming",
      "events",
      "tool_execution",
      "mcp",
      "subagents",
      "skills",
      "context",
      "cleanup",
      "diagnostics",
    ],
  ),
};

export const GROK_NATIVE_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:grok",
  harnessKind: "grok",
  label: "Grok Build Native Harness",
  vendor: "xai",
  official: true,
  transport: "acp-stdio",
  machineFacingBoundary: "grok agent stdio (ACP)",
  capabilities: capabilityMap(
    [...COMMON_STRUCTURED_CAPABILITIES, "mcp", "subagents", "context", "compaction"],
    [],
    [
      "discovery",
      "auth",
      "start",
      "resume",
      "multi_turn",
      "streaming",
      "events",
      "tool_execution",
      "mcp",
      "skills",
      "subagents",
      "cleanup",
      "diagnostics",
    ],
  ),
};

export const KIMI_NATIVE_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:kimi",
  harnessKind: "kimi",
  label: "Kimi Code Native Harness",
  vendor: "moonshot",
  official: true,
  transport: "acp-stdio",
  machineFacingBoundary: "kimi acp",
  capabilities: capabilityMap(
    [...COMMON_STRUCTURED_CAPABILITIES, "mcp", "subagents", "context", "compaction"],
    [],
    [
      "discovery",
      "auth",
      "start",
      "resume",
      "multi_turn",
      "streaming",
      "events",
      "tool_execution",
      "mcp",
      "skills",
      "subagents",
      "context",
      "cleanup",
      "diagnostics",
    ],
  ),
};

export const ANTIGRAVITY_NATIVE_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:antigravity",
  harnessKind: "antigravity",
  label: "Antigravity Native Harness",
  vendor: "google",
  official: true,
  transport: "official-stream-json",
  machineFacingBoundary: "agy --input-format stream-json --output-format stream-json",
  capabilities: capabilityMap(
    [
      "discovery",
      "auth",
      "profile",
      "start",
      "resume",
      "multi_turn",
      "streaming",
      "events",
      "tool_execution",
      "file_access",
      "shell_execution",
      "permission",
      "skills",
      "mcp",
      "subagents",
      "context",
      "interrupt",
      "cleanup",
      "diagnostics",
    ],
    ["compaction"],
    [
      "discovery",
      "auth",
      "start",
      "resume",
      "multi_turn",
      "streaming",
      "events",
      "tool_execution",
      "file_access",
      "skills",
      "mcp",
      "subagents",
      "context",
      "cleanup",
      "diagnostics",
    ],
  ),
};

export const DEEPSEEK_NATIVE_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:deepseek",
  harnessKind: "deepseek",
  label: "DeepSeek / DSH Native Harness",
  vendor: "deepseek",
  official: true,
  transport: "deepseek-json-rpc-stdio",
  machineFacingBoundary: "official dsh CLI (via JSON-RPC stdio)",
  capabilities: capabilityMap(
    [
      "discovery",
      "auth",
      "profile",
      "start",
      "resume",
      "multi_turn",
      "streaming",
      "events",
      "tool_execution",
      "file_access",
      "shell_execution",
      "permission",
      "mcp",
      "skills",
      "subagents",
      "context",
      "compaction",
      "interrupt",
      "cleanup",
      "diagnostics",
    ],
    [],
    ["discovery", "auth", "start", "events", "cleanup", "diagnostics"],
  ),
};

const DEEPSEEK_API_CAPABILITIES: Record<string, NativeHarnessCapabilityState> = {
  discovery: "supported+integrated",
  auth: "supported+integrated",
  start: "supported+integrated",
  multi_turn: "implementation missing",
  streaming: "supported+integrated",
  events: "supported+integrated",
  cleanup: "supported+integrated",
  diagnostics: "supported+integrated",
  resume: "implementation missing",
  tool_execution: "implementation missing",
  file_access: "implementation missing",
  shell_execution: "implementation missing",
  permission: "implementation missing",
  mcp: "implementation missing",
  skills: "implementation missing",
  subagents: "implementation missing",
  context: "implementation missing",
  compaction: "implementation missing",
  interrupt: "implementation missing",
};

export const DEEPSEEK_API_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:deepseek-api",
  harnessKind: "deepseek-api",
  label: "DeepSeek API Runtime",
  vendor: "deepseek",
  official: false,
  transport: "openai-compatible-http",
  machineFacingBoundary: "OpenAI-compatible HTTPS chat/completions",
  capabilities: DEEPSEEK_API_CAPABILITIES,
};

export const OPENCODE_NATIVE_HARNESS_DESCRIPTOR: NativeHarnessDescriptor = {
  id: "native-harness:opencode",
  harnessKind: "opencode",
  label: "OpenCode Native Harness",
  vendor: "opencode",
  official: true,
  transport: "official-http-sse",
  machineFacingBoundary: "opencode serve (HTTP/OpenAPI + SSE)",
  capabilities: {
    ...capabilityMap([
      "auth",
      "profile",
      "multi_turn",
      "streaming",
      "tool_execution",
      "file_access",
      "shell_execution",
      "permission",
      "mcp",
      "skills",
      "context",
      "compaction",
    ]),
    discovery: "supported+integrated",
    start: "supported+integrated",
    resume: "supported+integrated",
    events: "supported+integrated",
    interrupt: "supported+integrated",
    cleanup: "supported+integrated",
    diagnostics: "supported+integrated",
  },
};

export const NATIVE_HARNESS_DESCRIPTORS = {
  codex: CODEX_NATIVE_HARNESS_DESCRIPTOR,
  grok: GROK_NATIVE_HARNESS_DESCRIPTOR,
  kimi: KIMI_NATIVE_HARNESS_DESCRIPTOR,
  antigravity: ANTIGRAVITY_NATIVE_HARNESS_DESCRIPTOR,
  deepseek: DEEPSEEK_NATIVE_HARNESS_DESCRIPTOR,
  "deepseek-api": DEEPSEEK_API_HARNESS_DESCRIPTOR,
  opencode: OPENCODE_NATIVE_HARNESS_DESCRIPTOR,
} as const;
